### ISSUE TITLE
Syntax changes

### ISSUE THREAD

**Issue by Veltas** [titan-lang/titan-lang-docs#4]
I'm not sure how close you want Titan to be to Lua. I think there are compelling reasons to keep as similar a syntax as possible, to make the relationship as clear as possible. However, you may be able to 'sell' this language as based on Lua anyway without keeping the syntax too exact. If you're open to changing some of the original Lua syntax then there are a few obvious things that I see people complain about, and that might actually attract some people in the first place:

1. `fn` for `function`
2. `!=` for `~=`

Also, perhaps more controversially, you could replace *start*...`end` with `{`...`}`.

```lua
local function factorial(n)
  if n <= 0 then return 1 end
  return n * factorial(n-1)
end
```

```
local fn factorial(n) {
  if n <= 0 { return 1 }
  return n * factorial(n-1)
}
```

The `fn` and `{}` make lambda functions a lot nicer:

```lua
return function (x) return x<n end
```

```
return fn (x) { return x<n }
```

Also I personally dislike the way `end end end` looks trailing at the end of a structured function. I think it bulks the appearance of the code out unnecessarily, and is one of the first things I notice people remark about when I'm showing them Lua. I (like most people) am used to seeing `} } }` cascading at the end of a function, but it especially looks better if you want the option to space nested structures with less levels:

```lua
for j = 1,10 do for i = 1,10 do
  a[j][i] = i*j
end end
```

```
for j = 1,10 { for i = 1,10 {
  a[j][i] = i*j
}}
```

Anyway, just an idea, I think this could make Titan more attractive to people, but it might also detract from your goals. I certainly think `{` and `}` make the structure more visually obvious at a glance, regardless of syntax highlighting and how the code is written.

I'm not sure if the `{`..`}` idea will create ambiguous syntax against table constructors, if it does I'm sure there's a sensible way to resolve that without hurting the syntax too much. I certainly wouldn't suggest changing the syntax of table constructors, since I think that's probably one of the nicest things from Lua.

**Comment by hishamhm** [comment]
Hi, thank you for the feedback!

> I'm not sure how close you want Titan to be to Lua. I think there are compelling reasons to keep as similar a syntax as possible, to make the relationship as clear as possible. 

Titan is definitely its own language and not a Lua dialect, but being related to the Lua ecosystem, we want to keep it syntactically in the same ballpark (like all C-family languages use `{`/`}` and all Pascal-family languages use `begin`/`end`, for example). I believe one principle we're following is that things will look the same as Lua when they have the same meaning. This means we don't intend to make cosmetic changes to things like keywords (`function`, `end`) and operators (`~=`). When we add new concepts that do not exist in Lua, we will add new syntax, but we'll only do it when necessary to avoid confusion. Cheers!
